name: tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/rails-6-1.gemfile
          - gemfiles/rails-6-0.gemfile
        ruby:
          - '3.0'
          - '2.7'
          - '2.6'
        exclude:
          - ruby: '3.0'
            gemfile: gemfiles/rails-6-0.gemfile
          - ruby: '2.6'
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
